### ISSUE TITLE
Base Python Image changed

### ISSUE THREAD

**Issue by sumit0k** [davidgasquez/dbt-docker#2]
Hi @davidgasquez,

I want to thank you for your contribution for dbt docker image.

Your recent commit https://github.com/davidgasquez/dbt-docker/commit/664b398e76a558b7156188e623d7d7a41d63a09c where you changed base `python` to `3` instead of `3.6` breaks pipeline where python version `3.6` is expected as newer versions contains breaking changes for many plugins. 

If possible could you please release a docker tag with 3.6 base python?

**Comment by davidgasquez** [comment]
Ups! Hey @sumitkumar1209, I assumed forward compatibility. Sorry for the troubles I might have caused. I should have checked that everything was working. 

Just reverted the commit. I'll keep the `3.6` base image for some time while these bugs are fixed. 

Thanks for reporting. Happy `dbt`ing!
