### ISSUE TITLE
Dockerfile is not what is in davidgasquez/dbt?

### ISSUE THREAD

**Issue by nkijak** [davidgasquez/dbt-docker#3]
When I run 
```bash
docker run --rm -it \
  -v $PWD:/dbt \
  -v $PWD/deployment.profiles.yml:/home/dbt/.dbt/profiles.yml \
davidgasquez/dbt:latest bash
```
The user is `dbt`, permissions on `/dbt` are `dbt:users` and everything generally works.  

When I build the Dockerfile in this repo and run the same way, the user is `root`, permissions are `root:root` and I can't get dbt to run.

How do the extra steps happen?   Or is this not the repo for `davidgasquez/dbt:latest` on hub.docker.com?

**Comment by davidgasquez** [comment]
Hey @nkijak! I recently stopped using `latest` and replaced it with the `dbt` version I wanted to run. For example, `davidgasquez/dbt:13.0.0`. 

That said, the `latest` image should actually represent the latest `dbt` package so [I've made some changes and it should work from now on](https://github.com/davidgasquez/dbt-docker/commit/0a1be86e4a3db085a0a0248dcd8db40d3d251950).

Let me know if you hit any snags and thanks for reporting this issue! :raised_hands:

**Comment by nkijak** [comment]
I see that if I pull down `:0.13.0` I now have the same set of issues with my hand built one.  

The volume for the profiles.yml file is incorrect in the README then?   Since there's no dbt user anymore, the mount of `.dbt` should be somewhere else?   
```
docker run --rm -it -v $PWD:/dbt -v $HOME/.dbt/:/home/dbt/.dbt/profiles.yml davidgasquez/dbt:0.13.0 bash
root@7246d5aa3ec4:/dbt# dbt compile
Running with dbt=0.13.0
Encountered an error while reading the project:
Runtime Error
  Could not find profile named 'default'
Encountered an error:
Runtime Error
  Could not run dbt
```

~~For the life of me I can't figure out where that should be, but with your older image that had a dbt user it was 💯.   (So I was really hoping the fix here was a different dockerfile)~~

Finally got it, huge portion of the issue was my misunderstanding what a profile was.  But, unless there's another bonehead thing I'm doing, the README example should be 
```
docker run --rm -it \
  -v $PWD:/dbt \
  -v $PWD/deployment.profiles.yml:/root/.dbt/profiles.yml \
davidgasquez/dbt:latest bash
```

**Comment by davidgasquez** [comment]
Nice! You're totally right, the _README_ command was not correct. I've updated it with your command and I think it works now. 

Thanks for getting back with a solution!
